# -*- coding: utf-8 -*-
"""mikolaj2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NbnYJ3e0h45BmNneXWSr1a_6hUvftI8G
"""

import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np

st.set_page_config(layout="centered")
st.title("🎅 Święty Mikołaj w Streamlit (Matplotlib)")

def draw_santa():
    """Funkcja rysująca schematycznego Świętego Mikołaja za pomocą Matplotlib."""

    # Ustawienia figury (Zamiast plt.subplots używamy tylko plt.figure, a Streamlit zajmie się resztą)
    fig, ax = plt.subplots(figsize=(6, 10))
    ax.set_xlim(0, 10)
    ax.set_ylim(-3, 9) # Zmieniona oś Y, aby była w całości widoczna
    ax.set_aspect('equal')
    ax.axis('off')

    # --- ELEMENTY GŁOWY I CZAPKI ---

    # Czapka (Czerwony Kaptur - Dół)
    kaptur_dol = patches.Rectangle((3.5, 6.5), 3, 1, color='red', zorder=3)
    ax.add_patch(kaptur_dol)

    # Szczyt czapki (Trójkąt)
    czapka_x = np.array([4, 6, 5])
    czapka_y = np.array([7.5, 7.5, 9])
    ax.fill(czapka_x, czapka_y, color='red', zorder=3)

    # Puszysta kulka na czapce
    kulka = patches.Circle((5, 9), radius=0.3, color='white', zorder=4)
    ax.add_patch(kulka)

    # Puszyste futerko czapki
    futerko = patches.Rectangle((3, 6.3), 4, 0.4, color='white', zorder=4)
    ax.add_patch(futerko)

    # Głowa (Koło)
    glowa = patches.Circle((5, 5), radius=1.3, color='peachpuff', zorder=2)
    ax.add_patch(glowa)

    # Oczy i Nos
    ax.plot(4.4, 5.5, 'o', markersize=4, color='black', zorder=5)
    ax.plot(5.6, 5.5, 'o', markersize=4, color='black', zorder=5)
    nos = patches.Circle((5, 5), radius=0.2, color='brown', zorder=5)
    ax.add_patch(nos)

    # Broda (Trójkąt)
    broda_x = np.array([3.5, 6.5, 5])
    broda_y = np.array([4, 4, 2])
    ax.fill(broda_x, broda_y, color='white', zorder=1)

    # --- TUŁÓW, RĘCE I NOGI ---

    # 1. TUŁÓW
    tulow = patches.Rectangle((3, 0), 4, 4, color='red', zorder=1)
    ax.add_patch(tulow)

    # 2. FUTRO NA TUŁOWIU
    futerko_tulow = patches.Rectangle((3, 3.5), 4, 0.5, color='white', zorder=2)
    ax.add_patch(futerko_tulow)

    # 3. PASEK
    pasek = patches.Rectangle((3, 2.8), 4, 0.5, color='black', zorder=3)
    ax.add_patch(pasek)

    # 4. KLAMRA PASKA
    klamra = patches.Rectangle((4.5, 2.9), 1, 0.3, color='gold', zorder=4)
    ax.add_patch(klamra)

    # 5. RĘCE
    reka_l = patches.Rectangle((1, 2.5), 2, 0.8, color='red', zorder=1)
    ax.add_patch(reka_l)
    reka_p = patches.Rectangle((7, 2.5), 2, 0.8, color='red', zorder=1)
    ax.add_patch(reka_p)

    # 6. RĘKAWICZKI
    rekawiczka_l = patches.Circle((1, 2.9), radius=0.4, color='white', zorder=5)
    ax.add_patch(rekawiczka_l)
    rekawiczka_p = patches.Circle((9, 2.9), radius=0.4, color='white', zorder=5)
    ax.add_patch(rekawiczka_p)

    # 7. NOGI (Spodnie)
    noga_l = patches.Rectangle((3.5, -2), 1, 2, color='darkred', zorder=1)
    ax.add_patch(noga_l)
    noga_p = patches.Rectangle((5.5, -2), 1, 2, color='darkred', zorder=1)
    ax.add_patch(noga_p)

    # 8. BUTY
    but_l = patches.Rectangle((3, -3), 1.5, 1, color='black', zorder=2)
    ax.add_patch(but_l)
    but_p = patches.Rectangle((5.5, -3), 1.5, 1, color='black', zorder=2)
    ax.add_patch(but_p)

    # --- WYŚWIETLENIE W STREAMLIT ---

    # Zastępujemy plt.show() funkcją Streamlit
    st.pyplot(fig)


# Uruchomienie funkcji rysującej Mikołaja
draw_santa()